version: "3"

services:
  node-app:
    # Build from the Dockerfile in the current directory (server)
    build:
      context: .
      dockerfile: Dockerfile
    image: not-alone-backend:latest
    container_name: not-alone-backend
    # Map host port 3000 to container port 3000
    ports:
      - "3000:3000"
    # Inject environment variables from .env in /server (if present)
    env_file:
      - .env
    restart: always
