# Use Node 16 (LTS) as base
FROM node:20

# Set the working directory in the container
WORKDIR /Server

# Copy package JSON files first (for better Docker caching)
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the rest of your application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Command to run your app
CMD ["npm", "start"]
